#ifndef BOILERCONTROLLER_FORM_COLORS_H
#define BOILERCONTROLLER_FORM_COLORS_H

#include <Fonts/FreeSans12pt7b.h>
#include <Fonts/FreeSans9pt7b.h>

#define FORM_FONT (&FreeSans12pt7b)
#define FORM_LABEL_FONT (&FreeSans9pt7b)
#define FORM_FIELD_HEIGHT 28
#define FORM_LABEL_HEIGHT 18
#define FORM_LABEL_FIELD_GAP 4
#define FORM_TEXT_PAD_X 6
#define FORM_TEXT_BASELINE 20
#define FORM_LABEL_BASELINE 14
#define FORM_MAX_VALUE_LEN 64
#define FORM_DROPDOWN_ROW_HEIGHT 26
#define FORM_DROPDOWN_MAX_OPTIONS 16

#define FORM_COLOR_TEXT 0x0000
#define FORM_COLOR_BORDER 0xC618
#define FORM_COLOR_BG_FOCUSED 0xFFFF
#define FORM_COLOR_BG_UNFOCUSED 0xEF7D
#define FORM_COLOR_LABEL_BG 0xEF7D
#define FORM_COLOR_DROPDOWN_LIST_BG 0xFFFF
#define FORM_COLOR_DROPDOWN_SEL_BG 0xCE79

#endif
