#include "Logger.h"
#include "pins.h"

#define PWM_MAX_WIDTH 1023

#define CON_DEBUG_LEVEL_ALL 1
#define LOG_LEVEL_DETAIL_DEBUG 0
#define LOG_LEVEL_DEBUG 1
#define LOG_LEVEL_INFO 2
#define LOG_LEVEL_WARNING 3
#define LOG_LEVEL_ERROR 4
#define LOG_LEVEL_NOTHING 5


#define T_SENS_INDEX_INTERNAL 9
#define T_SENS_INDEX_CORE 0
#define T_SENS_INDEX_OUTPUT_FLOW 1
#define T_SENS_INDEX_INPUT_FLOW 2
#define T_SENS_INDEX_ACC_TOP 3
#define T_SENS_INDEX_ACC_MID_HI 4
#define T_SENS_INDEX_ACC_MID_LO 5
#define T_SENS_INDEX_ACC_BOTTOM 6
#define T_SENS_INDEX_FORWARD_FLOW 7
#define T_SENS_INDEX_BACKWARD_FLOW 8


/**
 * Уровень логирования
 */
#define LOG_LEVEL LOG_LEVEL_INFO

#define CON_DEBUG

#define WIFI_DEFAULT_SID "HKEE"
#define WIFI_DEFAULT_HOST_NAME "base"
#define WIFI_DEFAULT_PASSWORD "jj3PLPjj"

#define WATER_ENERGY_PER_LTR_PER_GRAD 4200.0D
#define JOUL_PER_KWTCH 3600000.0D
#define LOWEST_TEMPERATURE_FOR_ACCUMULATOR 35.0D
