#include "Logger.h"

#define PWM_MAX_WIDTH 1023

#define CON_DEBUG_LEVEL_ALL 1
#define LOG_LEVEL_DETAIL_DEBUG 0
#define LOG_LEVEL_DEBUG 1
#define LOG_LEVEL_INFO 2
#define LOG_LEVEL_WARNING 3
#define LOG_LEVEL_ERROR 4
#define LOG_LEVEL_NOTHING 5


#define T_SENS_INDEX_CORE 0
#define T_SENS_INDEX_OUTPUT_FLOW 1
#define T_SENS_INDEX_INPUT_FLOW 2
#define T_SENS_INDEX_ACC_TOP 3
#define T_SENS_INDEX_ACC_MID_HI 4
#define T_SENS_INDEX_ACC_MID_LO 5
#define T_SENS_INDEX_ACC_BOTTOM 6
#define T_SENS_INDEX_FORWARD_FLOW 7
#define T_SENS_INDEX_BACKWARD_FLOW 8


/**
 * Уровень логирования
 */
#define LOG_LEVEL LOG_LEVEL_INFO

#define CON_DEBUG

#define WIFI_DEFAULT_SID "HOME"
#define WIFI_DEFAULT_HOST_NAME "base"
#define WIFI_DEFAULT_PASSWORD "15121820"

#define SMOKE_SERVO_PIN 25
#define OXYGEN_SERVO_PIN 26
#define UPPER_SERVO_PIN 27

#define EMERGENCY_VALVE_PIN 0

#define PUMP_1_PIN 13
#define PUMP_2_PIN 12

#define ONE_WIRE_PIN 14
#define FLOW_SENSOR_PIN 39

#define DISPLAY_CS_PIN 17
#define DISPLAY_DC_PIN 15
#define DISPLAY_RST_PIN 16

#define MAIN_DOOR_SENSOR_PIN 34

#define WATER_ENERGY_PER_LTR_PER_GRAD 4200
