#include "Logger.h"

#define PWM_MAX_WIDTH 1023

#define CON_DEBUG_LEVEL_ALL 1
#define LOG_LEVEL_DETAIL_DEBUG 0
#define LOG_LEVEL_DEBUG 1
#define LOG_LEVEL_INFO 2
#define LOG_LEVEL_WARNING 3
#define LOG_LEVEL_ERROR 4
#define LOG_LEVEL_NOTHING 5

#define ONE_WIRE_PIN 14


#define CORE_SENSOR_INDEX 0
#define OUTPUT_FLOW_SENSOR_INDEX 1
#define INPUT_FLOW_SENSOR_INDEX 2
#define ACC_TOP_SENSOR_INDEX 3
#define ACC_MID_HI_SENSOR_INDEX 4
#define ACC_MID_LO_SENSOR_INDEX 5
#define ACC_BOTTOM_SENSOR_INDEX 6
#define FORWARD_FLOW_SENSOR_INDEX 7
#define BACKWARD_FLOW_SENSOR_INDEX 8


/**
 * Уровень логирования
 */
#define LOG_LEVEL LOG_LEVEL_INFO

#define CON_DEBUG

#define WIFI_DEFAULT_SID "HOME"
#define WIFI_DEFAULT_HOST_NAME "base"
#define WIFI_DEFAULT_PASSWORD "15121820"

#define SMOKE_SERVO_PIN 25
#define OXYGEN_SERVO_PIN 26
#define UPPER_SERVO_PIN 27

#define PUMP_1_PIN 13
#define PUMP_2_PIN 12
